# Generated by Django 5.2.7 on 2025-11-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_options_remove_servicio_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa del servicio', null=True, upload_to='servicios/', verbose_name='Imagen del Servicio'),
        ),
    ]
