# Generated by Django 5.2.6 on 2025-11-17 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0004_reserva_estado_pago_alter_reserva_comprobante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_inicial', models.DecimalField(decimal_places=2, help_text='Monto inicial en efectivo al abrir la caja', max_digits=10)),
                ('total_ingresos_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_egresos_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ingresos_otros', models.DecimalField(decimal_places=2, default=0, help_text='Total ingresos en tarjeta, transferencia, etc', max_digits=10)),
                ('total_egresos_otros', models.DecimalField(decimal_places=2, default=0, help_text='Total egresos en tarjeta, transferencia, etc', max_digits=10)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo que debería haber en caja', max_digits=10)),
                ('efectivo_real', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo contado al cerrar', max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia entre efectivo esperado y real', max_digits=10)),
                ('desglose_metodos', models.JSONField(default=dict, help_text='Desglose de movimientos por método de pago')),
                ('desglose_categorias', models.JSONField(default=dict, help_text='Desglose de movimientos por categoría')),
                ('cantidad_movimientos', models.IntegerField(default=0)),
                ('cantidad_ingresos', models.IntegerField(default=0)),
                ('cantidad_egresos', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('esta_cerrado', models.BooleanField(default=True)),
                ('usuario_apertura', models.ForeignKey(blank=True, help_text='Usuario que abrió la caja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_apertura', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, help_text='Usuario que cerró la caja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_cierre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transferencia_esperada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mercadopago_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seña_esperada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_cierre_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_cierre_transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_cierre_mercadopago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_cierre_seña', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia_mercadopago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia_seña', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ingresos_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_egresos_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_apertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_abiertos', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercadopago', 'Mercado Pago'), ('seña', 'Seña')], default='efectivo', max_length=20)),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios'), ('productos', 'Productos'), ('gastos', 'Gastos'), ('sueldos', 'Sueldos'), ('alquiler', 'Alquiler'), ('servicios_publicos', 'Servicios Públicos'), ('otros', 'Otros')], default='servicios', max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('comprobante', models.ImageField(blank=True, help_text='Comprobante del movimiento', null=True, upload_to='comprobantes_caja/')),
                ('es_editable', models.BooleanField(default=True, help_text='Si está en un turno cerrado, no se puede editar')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('barbero', models.ForeignKey(blank=True, help_text='Barbero asociado al movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
                ('cierre_caja', models.ForeignKey(blank=True, help_text='Cierre al que pertenece este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='caja.cierrecaja')),
                ('reserva', models.ForeignKey(blank=True, help_text='Reserva asociada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='reservas.reserva')),
                ('usuario_registro', models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(blank=True, help_text='Turno al que pertenece este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_turno', to='caja.turnocaja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['-fecha_cierre'], name='caja_cierre_fecha_c_4a05ed_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['-fecha_creacion'], name='caja_movimi_fecha_c_89b466_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['tipo', 'categoria'], name='caja_movimi_tipo_643bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['cierre_caja'], name='caja_movimi_cierre__a591d2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['turno'], name='caja_movimi_turno_i_74a451_idx'),
        ),
    ]
